language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t satyarthshankar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satyarthshankar/docker-react npm run test